archive:
  replacements:
    amd64: x86_64

brew:
  github:
    owner: flow-lab
    name: flow-tap
  folder: Formula
  homepage: "https://www.flowlab.no/"
  description: "AWS tooling for faster development."
  test: |
    system "#{bin}/flow --version"

s3:
- bucket: flowlab-no-artifact-public
  region: eu-west-1
  profile: "cloud-formation@flowlab-development"
  acl: public-read

snapcraft:
  name: flow
  summary: AWS tooling.
  description: |
    Tooling for AWS development.

  grade: stable
  confinement: strict

  apps:
    flow:
      plugs: ["home", "network"]