brew:
  github:
    owner: flow-lab
    name: flow-tap
  folder: Formula
  homepage: "https://www.flowlab.no/"
  description: "AWS tooling for faster development."
  test: |
    system "#{bin}/flow --version"

s3:
- bucket: flow-lab-artifact-public
  region: eu-west-1
  profile: cloud-formation@flowlab-development
  acl: public-read