brew:
  github:
    owner: flow-lab
    name: flow-tap
  folder: Formula
  homepage: "https://www.flowlab.no/"
  description: "AWS tooling for faster development."
  test: |
    system "#{bin}/flow --version"