version: 2

builds:
  - binary: flow
    main: ./cmd/flow/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm64

before:
  hooks:
    - make deps
    - make test

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

brews:
  - name: flow
    repository:
      owner: flow-lab
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://www.flowlab.no/"
    description: "AWS tooling for faster development."
    test: |
      system "#{bin}/flow --version"
