brew:
  github:
    owner: flow-lab
    name: flow-tap
  folder: Formula
  homepage: "https://www.flowlab.no/"
  description: "AWS tooling for faster development."
  test: |
    system "#{bin}/flow --version"

s3:
- bucket: flowlab-no-artifact-public
  region: eu-west-1
  profile: "cloud-formation@flowlab-development"
  acl: public-read

snapcraft:
  name: flow
  version: git
  summary: AWS tooling.
  description: |
    Tooling for AWS development.

  grade: stable
  confinement: strict

  parts:
    flow:
      source: .
      plugin: go
      go-importpath: github.com/flow-lab/flow

  apps:
    flow:
      command: flow