archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

brew:
  github:
    owner: flow-lab
    name: flow-tap
  folder: Formula
  homepage: "https://www.flowlab.no/"
  description: "AWS tooling for faster development."
  test: |
    system "#{bin}/flow --version"

s3:
  - bucket: flowlab-no-artifact-public
    region: eu-west-1
    profile: "cloudformation@flowlab-development"
    acl: public-read
