brew:
  # Name template of the recipe
  # Default to project name
  name: flow

  # Reporitory to push the tap to.
  github:
    owner: flow-lab
    name: flow-tap

  # Allows you to set a custom download strategy.
  # Default is empty.
  download_strategy: GitDownloadStrategy

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: krzysztof
    email: krzysztof@flowlab.no

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Caveats for the user of your binary.
  # Default is empty.
  # caveats: "How to use this binary"

  # Your app's homepage.
  # Default is empty.
  homepage: "https://www.flowlab.no/"

  # Your app's description.
  # Default is empty.
  description: "AWS tooling for faster development."

  # Setting this will prevent goreleaser to actually try to commit the updated
  # formula - instead, the formula file will be stored on the dist folder only,
  # leaving the responsibility of publishing it to the user.
  # Default is false.
  skip_upload: false

  # Packages your package depends on.
#  dependencies:
#    - git
#    - zsh

  # Packages that conflict with your package.
#  conflicts:
#    - svn
#    - bash

  # Specify for packages that run as a service.
  # Default is empty.
#  plist: |
#    <?xml version="1.0" encoding="UTF-8"?>
#    ...

  # So you can `brew test` your formula.
  # Default is empty.
  test: |
    system "#{bin}/flow --version"

  # Custom install script for brew.
  # Default is 'bin.install "program"'.
#  install: |
#    bin.install "program"
#    ...