env:
  - GO111MODULE=on

builds:
  - binary: flow
    main: ./cmd/flow/main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm64
before:
  hooks:
    - make deps
    - make test

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: flow
    tap:
      owner: flow-lab
      name: flow-tap
    folder: Formula
    homepage: "https://www.flowlab.no/"
    description: "AWS tooling for faster development."
    test: |
      system "#{bin}/flow --version"
