name: flow
version: git
summary: AWS tooling.
description: |
  Tooling for AWS development.

grade: stable
confinement: classic

base: core18

parts:
  flow:
    plugin: nil
    source: .
    build-snaps: [go]
    build-packages: [gcc,make]
    build-attributes: [no-patchelf]
    override-build: |
      export GOBIN=${PWD}/bin
      export GO111MODULE=on
      export CGO_ENABLED=0
      make install
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      cp bin/flow $SNAPCRAFT_PART_INSTALL/bin

apps:
  flow:
    command: bin/flow
