name: flow
version: git
summary: AWS tooling.
description: |
  Tooling for AWS development.

grade: stable
confinement: classic

parts:
  flow:
    source: .
    plugin: go
    go-importpath: github.com/flow-lab/flow
    build-attributes: [no-patchelf]

apps:
  flow:
    command: bin/flow
