name: flow
version: git
summary: AWS tooling.
description: |
  Tooling for AWS development.

grade: stable
confinement: classic

base: core18

parts:
  flow:
    plugin: nil
    source: .
    build-snaps: [go]
    build-packages: [gcc]
    build-attributes: [no-patchelf]
    override-build: |
      export GOBIN=$SNAPCRAFT_PART_INSTALL/bin
      export GO111MODULE=on
      export CGO_ENABLED=0
      go build ./...

apps:
  flow:
    command: bin/flow
