name: flow
version: git
summary: AWS tooling.
description: |
  Tooling for AWS development.

grade: stable
confinement: classic

base: core18

parts:
  flow:
    source: .
    plugin: go
    go-importpath: github.com/flow-lab/flow
    build-attributes: [no-patchelf]
    build-snaps: [go]
    build-packages: [gcc]
    build-environment:
    - GO11MODULE: "on"

apps:
  flow:
    command: bin/flow
