name: flow
version: git
summary: AWS tooling.
description: |
  Tooling for AWS development.

grade: stable
confinement: classic

base: core18

parts:
  flow:
    source: .
    plugin: go
    go-importpath: github.com/flow-lab/flow
    build-attributes: [no-patchelf]
    build-snaps: [go]
    build-packages: [gcc]
    override-build: |
      export GOBIN=$SNAPCRAFT_PART_INSTALL/bin
      export GO111MODULE=on
      export CGO_ENABLED=0
      make build

apps:
  flow:
    command: bin/flow
