name: flow
version: git
summary: AWS tooling.
description: |
  Tooling for AWS development.

grade: stable
confinement: devmode

parts:
  flow:
    source: .
    plugin: go
    go-importpath: github.com/flow-lab/flow

apps:
  flow:
    command: flow